---
- hosts: dockerhost

  tasks:

  - name: change owner ship
    command: sudo chmod 777 /var/run/docker.sock
    ignore_errors: yes

  - name: stop existing container
    command: docker stop regapp-server
    ignore_errors: yes

  - name: rm the container
    command: docker rm regapp-server
    ignore_errors: yes

  - name: rm image
    command: docker rmi ronyad/regapp
    ignore_errors: yes

  - name: create container
    command: docker run -d --name regapp-server -p 5000:5000 ronyad/regapp:latest