---
- hosts: ansible

  tasks:
  - name: create docker image
    command: docker build -t regapp:latest .
    args:
      chdir: /opt/docker

  - name: create tag to push
    command: docker tag regapp:latest ronyad/regapp:latest

  - name: push to image
    command: docker push ronyad/regapp:latest